version: "3"

services:
  webserver:
    build:
      context: ./webserver
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - database
      - phpmyadmin
    networks:
      - app-network
    restart: always

  database:
    image: mariadb:10.11
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
      MYSQL_USER: development1
      MYSQL_PASSWORD: password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: lemp_phpmyadmin
    environment:
      PMA_HOST: database
      PMA_USER: development1
      PMA_PASSWORD: password
    ports:
      - "8081:80"
    depends_on:
      - database
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data:
  node_modules:
